# Generated by Django 5.2.5 on 2026-01-23 13:58

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Template name (e.g., 'Custom Home Design')", max_length=100, unique=True)),
                ('description', models.TextField(help_text='What this template is for')),
                ('default_description', models.TextField(blank=True, help_text='Default invoice description')),
                ('default_notes', models.TextField(blank=True, help_text='Default payment terms/notes')),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Default tax rate (e.g., 6.25 for 6.25%)', max_digits=5)),
                ('days_until_due', models.PositiveIntegerField(default=30, help_text='Default payment terms in days')),
                ('default_line_items', models.JSONField(blank=True, default=list, help_text='Default line items for this template')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='email_sent_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times invoice was sent'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='email_sent_date',
            field=models.DateTimeField(blank=True, help_text='When invoice was last emailed', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='last_reminder_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_token',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='reminder_sent_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of reminder emails sent'),
        ),
    ]
