# Generated by Django 5.2.5 on 2026-01-23 13:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_invoice_reminder_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
