# Generated by Django 5.2.5 on 2026-01-23 13:58

from django.db import migrations
import uuid


def populate_payment_tokens(apps, schema_editor):
    """Populate payment_token for existing invoices."""
    Invoice = apps.get_model('billing', 'Invoice')
    for invoice in Invoice.objects.filter(payment_token__isnull=True):
        invoice.payment_token = uuid.uuid4()
        invoice.save(update_fields=['payment_token'])


def reverse_populate(apps, schema_editor):
    """Reverse migration - do nothing."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_invoice_payment_token'),
    ]

    operations = [
        migrations.RunPython(populate_payment_tokens, reverse_populate),
    ]
