# Generated by Django 5.2.5 on 2026-01-23 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_populate_payment_tokens'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.RemoveField(
            model_name='client',
            name='phone',
        ),
        migrations.AddField(
            model_name='client',
            name='country',
            field=models.CharField(blank=True, default='United States', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, help_text='Primary email address', max_length=254),
        ),
        migrations.AddField(
            model_name='client',
            name='email_secondary',
            field=models.EmailField(blank=True, help_text='Alternative email address', max_length=254, verbose_name='Secondary Email'),
        ),
        migrations.AddField(
            model_name='client',
            name='first_name',
            field=models.CharField(blank=True, help_text="Client's first name", max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='last_name',
            field=models.CharField(blank=True, help_text="Client's last name", max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='lead_source',
            field=models.CharField(blank=True, help_text='How did they find you? (referral, website, etc.)', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='phone_1',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone Number 1'),
        ),
        migrations.AddField(
            model_name='client',
            name='phone_1_type',
            field=models.CharField(choices=[('mobile', 'Mobile'), ('work', 'Work'), ('home', 'Home'), ('fax', 'Fax')], default='mobile', max_length=10, verbose_name='Phone 1 Type'),
        ),
        migrations.AddField(
            model_name='client',
            name='phone_2',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone Number 2'),
        ),
        migrations.AddField(
            model_name='client',
            name='phone_2_type',
            field=models.CharField(blank=True, choices=[('mobile', 'Mobile'), ('work', 'Work'), ('home', 'Home'), ('fax', 'Fax')], default='work', max_length=10, verbose_name='Phone 2 Type'),
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('lead', 'Lead'), ('archived', 'Archived')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='tax_id',
            field=models.CharField(blank=True, help_text='Business tax ID or EIN', max_length=50, verbose_name='Tax ID/EIN'),
        ),
        migrations.AddField(
            model_name='client',
            name='website',
            field=models.URLField(blank=True, help_text='Company website'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address_line1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Address Line 1'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address_line2',
            field=models.CharField(blank=True, help_text='Apt, suite, unit, building, floor, etc.', max_length=255, verbose_name='Address Line 2'),
        ),
        migrations.AlterField(
            model_name='client',
            name='company_name',
            field=models.CharField(blank=True, help_text='Company or business name', max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Portal login account (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='client',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='ZIP Code'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['last_name', 'first_name'], name='billing_cli_last_na_7aec41_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['email'], name='billing_cli_email_b0ba0e_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['company_name'], name='billing_cli_company_3fa204_idx'),
        ),
    ]
