# Generated by Django 5.2.5 on 2026-01-23 14:22

from django.db import migrations


def populate_client_data(apps, schema_editor):
    """Populate new client fields from linked user accounts."""
    Client = apps.get_model('billing', 'Client')
    
    for client in Client.objects.all():
        if client.user:
            # Populate from user account
            client.first_name = client.user.first_name or ''
            client.last_name = client.user.last_name or ''
            client.email = client.user.email or ''
            client.status = 'active'
            client.save(update_fields=['first_name', 'last_name', 'email', 'status'])


def reverse_populate(apps, schema_editor):
    """Reverse operation - do nothing since we're just copying data."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_alter_client_options_remove_client_phone_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_client_data, reverse_populate),
    ]
