# Generated by Django 5.2.5 on 2026-01-23 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_populate_client_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Employee's first name", max_length=100)),
                ('last_name', models.CharField(help_text="Employee's last name", max_length=100)),
                ('job_title', models.CharField(blank=True, help_text='Job title or position', max_length=100)),
                ('department', models.CharField(blank=True, help_text='Department', max_length=100)),
                ('email', models.EmailField(help_text='Work email address', max_length=254)),
                ('phone_1', models.CharField(blank=True, max_length=20, verbose_name='Primary Phone')),
                ('phone_1_type', models.CharField(choices=[('mobile', 'Mobile'), ('work', 'Work'), ('home', 'Home')], default='mobile', max_length=10, verbose_name='Phone Type')),
                ('phone_2', models.CharField(blank=True, max_length=20, verbose_name='Secondary Phone')),
                ('phone_2_type', models.CharField(blank=True, choices=[('mobile', 'Mobile'), ('work', 'Work'), ('home', 'Home')], default='work', max_length=10, verbose_name='Phone 2 Type')),
                ('address_line1', models.CharField(blank=True, max_length=255, verbose_name='Address Line 1')),
                ('address_line2', models.CharField(blank=True, max_length=255, verbose_name='Address Line 2')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('zip_code', models.CharField(blank=True, max_length=20, verbose_name='ZIP Code')),
                ('hire_date', models.DateField(blank=True, help_text='Date of hire', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave')], default='active', max_length=20)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('can_create_invoices', models.BooleanField(default=False, help_text='Can create and manage invoices')),
                ('can_manage_clients', models.BooleanField(default=False, help_text='Can add/edit client information')),
                ('can_view_reports', models.BooleanField(default=False, help_text='Can access financial reports')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this employee')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='Portal login account', on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='billing_emp_last_na_8eff59_idx'), models.Index(fields=['status'], name='billing_emp_status_cb61d2_idx')],
            },
        ),
    ]
