# Generated by Django 5.2.5 on 2026-01-23 16:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_employee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Provost Home Design', max_length=200)),
                ('company_email', models.EmailField(default='mike@provosthomedesign.com', max_length=254)),
                ('company_phone', models.CharField(default='508-243-7312', max_length=20)),
                ('company_address', models.TextField(default='7 Park St. Unit 1, Rehoboth, MA 02769')),
                ('sidebar_primary_color', models.CharField(default='#004080', help_text='Hex color for sidebar (e.g., #004080)', max_length=7)),
                ('sidebar_secondary_color', models.CharField(default='#002850', help_text='Hex color for sidebar gradient (e.g., #002850)', max_length=7)),
                ('portal_title', models.CharField(default='Client Portal', max_length=100)),
                ('employee_portal_title', models.CharField(default='Employee Portal', max_length=100)),
                ('allow_client_registration', models.BooleanField(default=False, help_text='Allow clients to self-register')),
                ('invoice_prefix', models.CharField(default='INV', help_text='Prefix for invoice numbers (e.g., INV-2024-001)', max_length=10)),
                ('default_payment_terms_days', models.IntegerField(default=30, help_text='Default payment terms in days', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('late_fee_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Late fee percentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('invoice_email_subject', models.CharField(default='New Invoice from {company_name}', help_text='Use {company_name}, {invoice_number} as placeholders', max_length=200)),
                ('invoice_reminder_days', models.IntegerField(default=7, help_text='Days before due date to send reminder', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('notify_on_new_client', models.BooleanField(default=True, help_text='Email notification when new client registers')),
                ('notify_on_payment', models.BooleanField(default=True, help_text='Email notification when payment received')),
                ('business_hours', models.TextField(default='Monday-Friday: 9:00 AM - 5:00 PM', help_text='Display business hours on portal')),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
