# Generated by Django 5.2.5 on 2026-01-23 17:12

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_systemsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_number', models.CharField(help_text='Job number in YYMMDD format (e.g., 260101 for Jan 1, 2026)', max_length=10, unique=True)),
                ('job_name', models.CharField(help_text='Project name or title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed project description')),
                ('start_date', models.DateField(blank=True, help_text='Project start date', null=True)),
                ('due_date', models.DateField(blank=True, help_text='Project due date', null=True)),
                ('completed_date', models.DateField(blank=True, help_text='Actual completion date', null=True)),
                ('billing_type', models.CharField(choices=[('flat_rate', 'Flat Rate'), ('hourly', 'Hourly Rate')], default='flat_rate', help_text='How this project is billed', max_length=20)),
                ('fixed_price', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed price for flat rate projects', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Hourly rate for hourly projects', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated hours for completion', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('actual_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Actual hours worked', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('quoted', 'Quoted'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='quoted', help_text='Current project status', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about the project')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(help_text='Client for this project', on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='billing.client')),
                ('created_by', models.ForeignKey(help_text='Staff member who created this project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-job_number'],
                'indexes': [models.Index(fields=['job_number'], name='billing_pro_job_num_fa353f_idx'), models.Index(fields=['client', 'status'], name='billing_pro_client__9beae4_idx'), models.Index(fields=['-created_at'], name='billing_pro_created_ba020f_idx')],
            },
        ),
    ]
