# Generated by Django 5.2.5 on 2026-01-23 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Optional: Link to project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='billing.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='job_number',
            field=models.CharField(help_text='Job number in YYMM## format (e.g., 260123 = Year 26, Month 01, Job #23)', max_length=10, unique=True),
        ),
    ]
