# Generated by Django 5.2.5 on 2026-01-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_proposaltemplate_proposal_proposallineitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Optional profile picture', null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Optional profile picture', null=True, upload_to='profile_pictures/'),
        ),
    ]
