# Generated by Django 5.2.5 on 2026-01-23 18:13

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_invoice_project_alter_project_job_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Template description')),
                ('default_title', models.CharField(blank=True, help_text='Default proposal title', max_length=255)),
                ('default_description', models.TextField(blank=True, help_text='Default proposal introduction')),
                ('default_terms', models.TextField(blank=True, help_text='Default terms and conditions')),
                ('default_valid_days', models.PositiveIntegerField(default=30, help_text='Days until proposal expires')),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('default_deposit_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('line_items_json', models.JSONField(blank=True, default=list, help_text='Default line items as JSON array')),
                ('is_active', models.BooleanField(default=True, help_text='Active templates appear in dropdown')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_number', models.CharField(help_text='Format: PROP-YYMM##', max_length=50, unique=True)),
                ('title', models.CharField(help_text='Proposal title or project name', max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('issue_date', models.DateField(default=django.utils.timezone.now, help_text='Date proposal was created')),
                ('valid_until', models.DateField(help_text='Proposal expiration date')),
                ('sent_date', models.DateTimeField(blank=True, help_text='When proposal was sent to client', null=True)),
                ('viewed_date', models.DateTimeField(blank=True, help_text='When client first viewed proposal', null=True)),
                ('accepted_date', models.DateTimeField(blank=True, help_text='When client accepted proposal', null=True)),
                ('rejected_date', models.DateTimeField(blank=True, help_text='When client rejected proposal', null=True)),
                ('description', models.TextField(blank=True, help_text='Proposal introduction and overview')),
                ('terms_and_conditions', models.TextField(blank=True, help_text='Terms, conditions, and payment details')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax rate as percentage (e.g., 7.5 for 7.5%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('deposit_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Deposit as percentage of total (e.g., 50 for 50%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Required deposit/retainer amount', max_digits=10)),
                ('accepted_by', models.CharField(blank=True, help_text='Name of person who accepted', max_length=200)),
                ('acceptance_signature', models.TextField(blank=True, help_text='Digital signature data (optional)')),
                ('acceptance_ip', models.GenericIPAddressField(blank=True, help_text='IP address of acceptance', null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes (not visible to client)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(help_text='Client receiving this proposal', on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='billing.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, help_text='Project created when proposal is accepted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='billing.project')),
            ],
            options={
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProposalLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Service or item description')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Price per unit', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='billing.proposal')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['proposal_number'], name='billing_pro_proposa_097090_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['client', 'status'], name='billing_pro_client__6df41b_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['status', 'valid_until'], name='billing_pro_status_5d6b45_idx'),
        ),
    ]
