# Generated by Django 5.2.5 on 2026-01-24 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_client_profile_picture_employee_profile_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='viewed_date',
            field=models.DateTimeField(blank=True, help_text='When the client last viewed this invoice', null=True),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Type of activity (viewed, commented, paid, etc.)', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Details about the activity')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, help_text='Client if activity is related to a client', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='billing.client')),
                ('invoice', models.ForeignKey(blank=True, help_text='Invoice if activity is related to an invoice', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='billing.invoice')),
                ('performed_by', models.ForeignKey(help_text='User or system that performed the activity', on_delete=django.db.models.deletion.SET_NULL, null=True, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, help_text='Project if activity is related to a project', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='billing.project')),
            ],
        ),
    ]
