# Generated by Django 5.2.5 on 2026-01-24 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_proposaltemplate_proposal_proposallineitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPlanFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(help_text="Display name for the file (e.g., 'Main Floor Plan.pdf')", max_length=255)),
                ('file_type', models.CharField(choices=[('floor_plan', 'Floor Plan'), ('elevation', 'Elevation'), ('site_plan', 'Site Plan'), ('structural', 'Structural Drawing'), ('electrical', 'Electrical Plan'), ('plumbing', 'Plumbing Plan'), ('rendering', '3D Rendering'), ('other', 'Other')], default='other', help_text='Type of plan file', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Optional description or notes about this file')),
                ('dropbox_link', models.URLField(help_text='Dropbox shared link (use direct download link: ?dl=1)', max_length=500)),
                ('version', models.CharField(blank=True, help_text="Version number or revision (e.g., 'Rev 3', 'v2.1')", max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide from client (useful for outdated versions)')),
                ('client', models.ForeignKey(help_text='Client who can access this file', on_delete=django.db.models.deletion.CASCADE, related_name='plan_files', to='billing.client')),
                ('project', models.ForeignKey(blank=True, help_text='Associated project (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_files', to='billing.project')),
                ('uploaded_by', models.ForeignKey(help_text='Staff member who added this file', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_files_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Plan File',
                'verbose_name_plural': 'Client Plan Files',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['client', 'is_active', '-uploaded_at'], name='billing_cli_client__7b4cb1_idx'), models.Index(fields=['project', 'is_active'], name='billing_cli_project_47c124_idx')],
            },
        ),
    ]
