# Generated by Django 5.2.5 on 2026-01-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_clientplanfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='portal_logo',
            field=models.ImageField(blank=True, help_text='Portal logo (displayed in sidebar and login pages). Falls back to phdlogo.svg if not set.', null=True, upload_to='brand/'),
        ),
    ]
