# Generated by Django 5.2.5 on 2026-01-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_systemsettings_portal_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='company_name_color',
            field=models.CharField(default='#004080', help_text='Color for company name text below logo (e.g., #004080)', max_length=7),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='logo_background_color',
            field=models.CharField(default='#FFFFFF', help_text='Background color for logo area (e.g., #FFFFFF for white)', max_length=7),
        ),
    ]
