# Generated by Django 5.2.5 on 2026-01-25 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_systemsettings_company_name_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='linked_invoice',
            field=models.OneToOneField(blank=True, help_text='Invoice generated from this proposal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_proposal', to='billing.invoice'),
        ),
    ]
