# Generated by Django 5.2.5 on 2026-01-25 19:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_proposal_linked_invoice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
            # ...existing code...
        # migrations.AddField(
        #     model_name='project',
        #     name='closed_date',
        #     field=models.DateTimeField(blank=True, help_text='When project was closed', null=True),
        # ),
        migrations.AddField(
            model_name='project',
            name='is_closed',
            field=models.BooleanField(default=False, help_text='Whether project is closed'),
        ),
    ]
