# Generated by Django 5.2.5 on 2026-01-25 20:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_add_project_closure_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
            # migrations.CreateModel(
            #     name='ExpenseCategory',
            #     fields=[ ... ],
            #     options={ ... },
            # ),
            # migrations.CreateModel(
            #     name='Expense',
            #     fields=[ ... ],
            #     options={ ... },
            # ),
    ]
