# Generated by Django 5.2.5 on 2026-01-26 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_client_profile_picture_employee_profile_picture'),
        ('billing', '0020_expensecategory_expense'),
    ]

    operations = [
    ]
