# Generated by Django 5.2.5 on 2026-01-26 15:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0021_merge_20260126_1018'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
            # migrations.CreateModel(
            #     name='Expense',
            #     fields=[ ... ],
            #     options={ ... },
            # ),
            # migrations.CreateModel(
            #     name='ExpenseCategory',
            #     fields=[ ... ],
            #     options={ ... },
            # ),
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Activities'},
        ),
        # migrations.RenameField(
        #     model_name='activity',
        #     old_name='timestamp',
        #     new_name='created_at',
        # ),
        # migrations.RemoveField(
        #     model_name='activity',
        #     name='action',
        # ),
        # migrations.RemoveField(
        #     model_name='activity',
        #     name='performed_by',
        # ),
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('note', 'Note'), ('call', 'Phone Call'), ('email', 'Email'), ('meeting', 'Meeting'), ('site_visit', 'Site Visit'), ('proposal_sent', 'Proposal Sent'), ('proposal_viewed', 'Proposal Viewed'), ('proposal_accepted', 'Proposal Accepted'), ('proposal_rejected', 'Proposal Rejected'), ('invoice_sent', 'Invoice Sent'), ('invoice_viewed', 'Invoice Viewed'), ('payment_received', 'Payment Received'), ('project_started', 'Project Started'), ('project_completed', 'Project Completed'), ('status_change', 'Status Change'), ('other', 'Other')], default='note', max_length=30),
        ),
        migrations.AddField(
            model_name='activity',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who logged this activity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='is_internal',
            field=models.BooleanField(default=False, help_text='Internal note (not visible to client)'),
        ),
        migrations.AddField(
            model_name='activity',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='Pin important activities to top'),
        ),
        migrations.AddField(
            model_name='activity',
            name='proposal',
            field=models.ForeignKey(blank=True, help_text='Associated proposal (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='billing.proposal'),
        ),
        migrations.AddField(
            model_name='activity',
            name='title',
            field=models.CharField(default='Untitled', help_text='Brief activity title', max_length=200),
            preserve_default=False,
        ),
        # migrations.AddField(
        #     model_name='project',
        #     name='closed_by',
        #     field=models.ForeignKey(blank=True, help_text='Staff member who closed this project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_projects', to=settings.AUTH_USER_MODEL),
        # ),
        # migrations.AddField(
        #     model_name='project',
        #     name='closed_date',
        #     field=models.DateTimeField(blank=True, help_text='When project was closed', null=True),
        # ),
        migrations.AlterField(
            model_name='activity',
            name='client',
            field=models.ForeignKey(help_text='Associated client', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='billing.client'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed notes or description'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='invoice',
            field=models.ForeignKey(blank=True, help_text='Associated invoice (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='billing.invoice'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Associated project (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='billing.project'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='viewed_date',
            field=models.DateTimeField(blank=True, help_text='When client first viewed invoice', null=True),
        ),
        # migrations.AddIndex(
        #     model_name='activity',
        #     index=models.Index(fields=['client', '-created_at'], name='billing_act_client__67a9df_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='activity',
        #     index=models.Index(fields=['project', '-created_at'], name='billing_act_project_efff7c_idx'),
        # ),
        # migrations.AddField(
        #     model_name='expense',
        #     name='approved_by',
        #     field=models.ForeignKey(blank=True, help_text='User who approved this', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL),
        # ),
        # migrations.AddField(
        #     model_name='expense',
        #     name='client',
        #     field=models.ForeignKey(blank=True, help_text='Associated client (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='billing.client'),
        # ),
        # migrations.AddField(
        #     model_name='expense',
        #     name='created_by',
        #     field=models.ForeignKey(help_text='User who submitted this', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_expenses', to=settings.AUTH_USER_MODEL),
        # ),
        # migrations.AddField(
        #     model_name='expense',
        #     name='project',
        #     field=models.ForeignKey(blank=True, help_text='Associated project (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='billing.project'),
        # ),
        # migrations.AddField(
        #     model_name='expense',
        #     name='category',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='billing.expensecategory'),
        # ),
        # migrations.AddIndex(
        #     model_name='expense',
        #     index=models.Index(fields=['-expense_date'], name='billing_exp_expense_d56562_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='expense',
        #     index=models.Index(fields=['status'], name='billing_exp_status_ddbf2b_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='expense',
        #     index=models.Index(fields=['project'], name='billing_exp_project_b95f35_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='expense',
        #     index=models.Index(fields=['client'], name='billing_exp_client__b4d338_idx'),
        # ),
    ]
