# Generated by Django 5.2.5 on 2026-01-27 13:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0022_expense_expensecategory_alter_activity_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Expense',
        #     fields=[ ... ],
        #     options={ ... },
        # ),
        # migrations.CreateModel(
        #     name='ExpenseCategory',
        #     fields=[ ... ],
        #     options={ ... },
        # ),
        migrations.RenameField(
            model_name='activity',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='action',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='performed_by',
        ),
        migrations.AddField(
            model_name='clientplanfile',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional attachment file (PDF, image, etc.)', null=True, upload_to='plan_attachments/'),
        ),
        # migrations.AddField(
        #     model_name='project',
        #     name='closed_by',
        #     field=models.ForeignKey(blank=True, help_text='Staff member who closed this project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_projects', to=settings.AUTH_USER_MODEL),
        # ),
        # migrations.AddField(
        #     model_name='project',
        #     name='closed_date',
        #     field=models.DateTimeField(blank=True, help_text='When project was closed', null=True),
        # ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['client', '-created_at'], name='billing_act_client__67a9df_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['project', '-created_at'], name='billing_act_project_efff7c_idx'),
        ),
        # migrations.AddField(
        #     model_name='expense',
        #     name='approved_by',
        #     field=models.ForeignKey(blank=True, help_text='User who approved this', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL),
        # ),
        # migrations.AddField(
        #     model_name='expense',
        #     name='client',
        #     field=models.ForeignKey(blank=True, help_text='Associated client (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='billing.client'),
        # ),
        # migrations.AddField(
        #     model_name='expense',
        #     name='created_by',
        #     field=models.ForeignKey(help_text='User who submitted this', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_expenses', to=settings.AUTH_USER_MODEL),
        # ),
        # migrations.AddField(
        #     model_name='expense',
        #     name='project',
        #     field=models.ForeignKey(blank=True, help_text='Associated project (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='billing.project'),
        # ),
        # migrations.AddField(
        #     model_name='expense',
        #     name='category',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='billing.expensecategory'),
        # ),
        # migrations.AddIndex(
        #     model_name='expense',
        #     index=models.Index(fields=['-expense_date'], name='billing_exp_expense_d56562_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='expense',
        #     index=models.Index(fields=['status'], name='billing_exp_status_ddbf2b_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='expense',
        #     index=models.Index(fields=['project'], name='billing_exp_project_b95f35_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='expense',
        #     index=models.Index(fields=['client'], name='billing_exp_client__b4d338_idx'),
        # ),
    ]
