# Generated by Django 5.2.5 on 2026-01-27 13:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0022_expense_expensecategory_alter_activity_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    operations = [
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['client', '-created_at'], name='billing_act_client__67a9df_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['project', '-created_at'], name='billing_act_project_efff7c_idx'),
        ),
    ]
        #    new_name='created_at',
