# Generated by Django 5.2.5 on 2026-01-27 14:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0026_expensecategory_project_closed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # The following operations are commented out because the tables/columns already exist in the database.
    operations = [
        # migrations.CreateModel(
        #     name='ExpenseCategory',
        #     fields=[ ... ],
        #     options={ ... },
        # ),
        # migrations.AddField(
        #     model_name='project',
        #     name='closed_by',
        #     field=models.ForeignKey(...),
        # ),
        # migrations.AddField(
        #     model_name='project',
        #     name='closed_date',
        #     field=models.DateTimeField(...),
        # ),
        # migrations.CreateModel(
        #     name='Expense',
        #     fields=[ ... ],
        #     options={ ... },
        # ),
    ]
