# Generated by Django 5.2.5 on 2026-01-27 15:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0030_expensecategory_project_closed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Expense',
        #     fields=[ ... ],
        #     options={ ... },
        # ),
        # migrations.CreateModel(
        #     name='ExpenseCategory',
        #     fields=[ ... ],
        #     options={ ... },
        # ),
        # migrations.RenameField(
        #     model_name='activity',
        #     old_name='timestamp',
        #     new_name='created_at',
        # ),
        # migrations.RemoveField(
        #     model_name='activity',
        #     name='action',
        # ),
        # migrations.RemoveField(
        #     model_name='activity',
        #     name='performed_by',
        # ),
        # migrations.AddField(
        #     model_name='clientplanfile',
        #     name='attachment',
        #     field=models.FileField(...),
        # ),
        # migrations.AddField(
        #     model_name='project',
        #     name='closed_by',
        #     field=models.ForeignKey(...),
        # ),
        # migrations.AddField(
        #     model_name='project',
        #     name='closed_date',
        #     field=models.DateTimeField(...),
        # ),
        # migrations.AddIndex(
        #     model_name='activity',
        #     index=models.Index(...),
        # ),
        # migrations.AddIndex(
        #     model_name='activity',
        #     index=models.Index(...),
        # ),
        # migrations.AddField(
        #     model_name='expense',
        #     name='approved_by',
        #     field=models.ForeignKey(...),
        # ),
        # migrations.AddField(
        #     model_name='expense',
        #     name='client',
        #     field=models.ForeignKey(...),
        # ),
        # migrations.AddField(
        #     model_name='expense',
        #     name='created_by',
        #     field=models.ForeignKey(...),
        # ),
        # migrations.AddField(
        #     model_name='expense',
        #     name='project',
        #     field=models.ForeignKey(...),
        # ),
        # migrations.AddField(
        #     model_name='expense',
        #     name='category',
        #     field=models.ForeignKey(...),
        # ),
        # migrations.AddIndex(
        #     model_name='expense',
        #     index=models.Index(...),
        # ),
        # migrations.AddIndex(
        #     model_name='expense',
        #     index=models.Index(...),
        # ),
        # migrations.AddIndex(
        #     model_name='expense',
        #     index=models.Index(...),
        # ),
        # migrations.AddIndex(
        #     model_name='expense',
        #     index=models.Index(...),
        # ),
    ]
