# Generated by Django 5.2.5 on 2026-10-07 12:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=200, unique=True)),
                ('channel', models.CharField(default='staff', max_length=30)),
                ('answers', models.JSONField(default=dict)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='WorkProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('street', models.CharField(blank=True, max_length=250)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('canonical_reference', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QueueState',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('last_reference_number', models.PositiveBigIntegerField(default=0)),
                ('last_queue_order', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='wq_singleton_state')],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_name', models.CharField(max_length=255)),
                ('storage_key', models.CharField(blank=True, max_length=1024)),
                ('legacy_drive_id', models.CharField(blank=True, max_length=200)),
                ('content_type', models.CharField(blank=True, max_length=150)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('categories', models.JSONField(default=list)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='workqueue.submission')),
            ],
        ),
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(editable=False, max_length=32, unique=True)),
                ('kind', models.CharField(choices=[('new', 'New Submission'), ('update', 'Update')], default='new', max_length=10)),
                ('project_context', models.CharField(blank=True, max_length=500)),
                ('contact_full_name', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=50)),
                ('billing_street', models.CharField(blank=True, max_length=250)),
                ('billing_city', models.CharField(blank=True, max_length=100)),
                ('billing_state', models.CharField(blank=True, max_length=50)),
                ('billing_zip', models.CharField(blank=True, max_length=20)),
                ('project_name', models.CharField(blank=True, max_length=200)),
                ('project_street', models.CharField(blank=True, max_length=250)),
                ('project_city', models.CharField(blank=True, max_length=100)),
                ('project_state', models.CharField(blank=True, max_length=50)),
                ('project_zip', models.CharField(blank=True, max_length=20)),
                ('service_needed', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('needs_information', 'Needs Information'), ('ready', 'Ready to Schedule'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('declined', 'Declined'), ('duplicate', 'Duplicate')], default='new', max_length=30)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('soon', 'Soon'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('queue_order', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('estimated_days', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('requested_deadline', models.DateField(blank=True, null=True)),
                ('committed_due_date', models.DateField(blank=True, null=True)),
                ('scheduled_start', models.DateField(blank=True, null=True)),
                ('estimated_completion', models.DateField(blank=True, null=True)),
                ('followup_date', models.DateField(blank=True, null=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('legacy_ref', models.CharField(blank=True, max_length=200)),
                ('submission_position', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('previous_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updates', to='workqueue.workitem')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_items', to='workqueue.workproject')),
            ],
            options={
                'ordering': ['queue_order', 'received_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='submission',
            name='work_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='workqueue.workitem'),
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40)),
                ('changes', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('work_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='workqueue.workitem')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_grants', to='workqueue.workproject')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_kind', models.CharField(choices=[('client', 'Client'), ('owner', 'Owner')], max_length=10)),
                ('recipient', models.EmailField(max_length=254)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('unknown', 'Needs reconciliation'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('provider_reference', models.CharField(blank=True, max_length=200)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='workqueue.submission')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('submission', 'recipient_kind'), name='wq_submission_notice_unique')],
            },
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['status', 'queue_order'], name='wq_status_order_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['queue_order', 'received_at', 'id'], name='wq_order_received_idx'),
        ),
        migrations.AddConstraint(
            model_name='workitem',
            constraint=models.CheckConstraint(condition=models.Q(('queue_order__gte', 1)), name='wq_order_positive'),
        ),
        migrations.AddConstraint(
            model_name='workitem',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['new', 'needs_information', 'ready', 'scheduled', 'in_progress', 'on_hold', 'completed', 'canceled', 'declined', 'duplicate'])), name='wq_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='workitem',
            constraint=models.CheckConstraint(condition=models.Q(('priority__in', ['normal', 'soon', 'urgent'])), name='wq_valid_priority'),
        ),
        migrations.AddConstraint(
            model_name='workitem',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['new', 'update'])), name='wq_valid_kind'),
        ),
        migrations.AddConstraint(
            model_name='projectaccess',
            constraint=models.UniqueConstraint(fields=('project', 'email'), name='wq_project_email_unique'),
        ),
    ]
