# Generated by Django 5.2.5 on 2026-10-07 13:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workqueue', '0002_seed_queue_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccessToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('digest', models.CharField(max_length=64, unique=True)),
                ('reference', models.CharField(blank=True, max_length=32)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='last_error',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='submission',
            name='owner_email',
            field=models.EmailField(blank=True, db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='notificationdelivery',
            name='recipient_kind',
            field=models.CharField(choices=[('client', 'Client'), ('owner', 'Owner'), ('signin', 'Sign-in')], max_length=10),
        ),
        migrations.AlterField(
            model_name='notificationdelivery',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='workqueue.submission'),
        ),
        migrations.CreateModel(
            name='PendingUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('intake_nonce', models.UUIDField(db_index=True)),
                ('session_digest', models.CharField(max_length=64)),
                ('original_name', models.CharField(max_length=255)),
                ('storage_key', models.CharField(max_length=1024, unique=True)),
                ('upload_key', models.CharField(blank=True, max_length=1024)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('content_type', models.CharField(max_length=150)),
                ('state', models.CharField(choices=[('reserved', 'Uploading'), ('ready', 'Ready'), ('attached', 'Submitted'), ('failed', 'Upload failed')], default='reserved', max_length=12)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('attachment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='workqueue.attachment')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='intake_claim', to='workqueue.workproject')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='workqueue.submission')),
            ],
        ),
    ]
