# Generated by Django 5.2.5 on 2026-10-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workqueue', '0004_backfill_staff_submission_owners'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingupload',
            name='sealed_key',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
