# Generated by Django 5.2.5 on 2026-10-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workqueue', '0007_seed_booking_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccesstoken',
            name='destination',
            field=models.CharField(choices=[('tracking', 'Tracking'), ('booking', 'Booking')], default='tracking', max_length=10),
        ),
    ]
