# Generated by Django 5.2.5 on 2026-10-07 14:35

import datetime
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workqueue', '0008_booking_signin_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='sync_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['pending', 'syncing', 'confirmed', 'attention', 'canceled', 'completed'])), name='wq_valid_appointment_state'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at', django.db.models.expressions.CombinedExpression(models.F('starts_at'), '+', models.Value(datetime.timedelta(seconds=1800))))), name='wq_30_minute_meeting'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_until', django.db.models.expressions.CombinedExpression(models.F('ends_at'), '+', models.Value(datetime.timedelta(seconds=1800))))), name='wq_30_minute_buffer'),
        ),
    ]
