# Generated by Django 5.2.5 on 2026-10-07 23:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workqueue', '0009_booking_worker_guards'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyQueueImport',
            fields=[
                ('digest', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('source_id', models.CharField(max_length=200)),
                ('payload', models.JSONField()),
                ('summary', models.JSONField(default=dict)),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
