# Generated by Django 5.2.5 on 2026-10-08 10:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workqueue', '0010_legacy_queue_import_archive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=5000)),
                ('followup_date', models.DateField(blank=True, null=True)),
                ('token', models.UUIDField(editable=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('delivery', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='information_request', to='workqueue.notificationdelivery')),
                ('work_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='information_requests', to='workqueue.workitem')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
