# Generated by Django 5.2.5 on 2026-10-08 11:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workqueue', '0011_informationrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('information_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='workqueue.informationrequest')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('work_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='information_response', to='workqueue.workitem')),
            ],
            options={
                'ordering': ['-verified_at', '-pk'],
            },
        ),
    ]
