# Generated by Django 5.2.5 on 2026-10-08 11:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workqueue', '0012_informationresponse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_status', models.CharField(choices=[('new', 'New'), ('needs_information', 'Needs Information'), ('ready', 'Ready to Schedule'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('declined', 'Declined'), ('duplicate', 'Duplicate')], max_length=30)),
                ('status', models.CharField(choices=[('new', 'New'), ('needs_information', 'Needs Information'), ('ready', 'Ready to Schedule'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('declined', 'Declined'), ('duplicate', 'Duplicate')], max_length=30)),
                ('item_version', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('delivery', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='status_milestone', to='workqueue.notificationdelivery')),
                ('work_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='milestones', to='workqueue.workitem')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'constraints': [models.UniqueConstraint(fields=('work_item', 'item_version'), name='wq_milestone_version_unique')],
            },
        ),
    ]
