# Generated by Django 5.2.5 on 2026-10-08 14:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workqueue', '0013_statusmilestone'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeDraft',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('session_digest', models.CharField(db_index=True, max_length=64)),
                ('answers', models.JSONField(default=dict)),
                ('files', models.JSONField(default=list)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
        ),
    ]
