# Generated by Django 5.2.5 on 2026-10-08 14:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workqueue', '0014_intakedraft'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='informationrequest',
            name='reminder_canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='informationrequest',
            name='reminder_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='informationrequest',
            name='reminder_delivery',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='information_reminder', to='workqueue.notificationdelivery'),
        ),
        migrations.AlterField(
            model_name='notificationdelivery',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('unknown', 'Needs reconciliation'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='CompletedDelivery',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('recipient', models.EmailField(max_length=254)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='completed_delivery', to='workqueue.notificationdelivery')),
                ('work_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='completed_deliveries', to='workqueue.workitem')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='CompletedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_name', models.CharField(max_length=255)),
                ('storage_key', models.CharField(max_length=1024)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='workqueue.completeddelivery')),
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='workqueue.pendingupload')),
            ],
        ),
    ]
