# Generated by Django 5.2.5 on 2026-10-08 14:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workqueue', '0015_informationrequest_reminder_canceled_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueWorkerHealth',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('run_token', models.UUIDField(null=True)),
                ('last_started', models.DateTimeField(null=True)),
                ('last_finished', models.DateTimeField(null=True)),
                ('last_success', models.DateTimeField(null=True)),
                ('failed_tasks', models.JSONField(default=list)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='wq_health_singleton')],
            },
        ),
    ]
