# Generated by Django 5.2.5 on 2026-10-10 13:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workqueue', '0016_queueworkerhealth'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('normalized_name', models.CharField(db_index=True, editable=False, max_length=200)),
                ('kind', models.CharField(choices=[('individual', 'Individual / homeowner'), ('company', 'Company')], default='individual', max_length=20)),
                ('billing_street', models.CharField(blank=True, max_length=250)),
                ('billing_city', models.CharField(blank=True, max_length=100)),
                ('billing_state', models.CharField(blank=True, max_length=50)),
                ('billing_zip', models.CharField(blank=True, max_length=20)),
                ('internal_notes', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merged_clients', to='workqueue.client')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('submitted_company', models.CharField(blank=True, max_length=200)),
                ('normalized_name', models.CharField(blank=True, db_index=True, editable=False, max_length=200)),
                ('normalized_phone', models.CharField(blank=True, db_index=True, editable=False, max_length=50)),
                ('normalized_company', models.CharField(blank=True, db_index=True, editable=False, max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='workqueue.client')),
            ],
            options={
                'ordering': ['full_name', 'email', 'id'],
            },
        ),
        migrations.AddField(
            model_name='workitem',
            name='client_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_items', to='workqueue.clientcontact'),
        ),
        migrations.CreateModel(
            name='ClientEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40)),
                ('changes', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='workqueue.client')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['individual', 'company'])), name='wq_client_kind'),
        ),
    ]
