# Generated by Django 5.2.5 on 2026-10-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workqueue', '0018_populate_crm_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcontact',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='archived_email',
            field=models.EmailField(blank=True, editable=False, max_length=254),
        ),
    ]
