# Generated by Django 5.2.5 on 2026-01-24 18:52
# Data migration to seed Freshbooks clients

import csv
import os
from django.db import migrations


def seed_freshbooks_clients(apps, schema_editor):
    """Import clients from Freshbooks CSV export."""
    User = apps.get_model('auth', 'User')
    Client = apps.get_model('billing', 'Client')
    
    # Path to CSV file (in project root)
    csv_path = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), 'Freshbooks Client Export.csv')
    
    # Check if CSV exists
    if not os.path.exists(csv_path):
        print(f"⚠️  Warning: CSV file not found at {csv_path}")
        print("   Skipping client import. To import clients later, run:")
        print("   python manage.py import_freshbooks_clients 'Freshbooks Client Export.csv'")
        return
    
    created_count = 0
    skipped_count = 0
    
    with open(csv_path, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        
        for row in reader:
            email = row.get('Email', '').strip().lower()
            first_name = row.get('First Name', '').strip()
            last_name = row.get('Last Name', '').strip()
            
            # Skip rows without email or first name
            if not email or not first_name:
                skipped_count += 1
                continue
            
            # Skip if user already exists
            if User.objects.filter(email=email).exists():
                skipped_count += 1
                continue
            
            # Generate username from email
            username = email.split('@')[0]
            
            # Handle duplicate usernames
            base_username = username
            counter = 1
            while User.objects.filter(username=username).exists():
                username = f"{base_username}{counter}"
                counter += 1
            
            # Create user
            user = User.objects.create(
                username=username,
                email=email,
                first_name=first_name,
                last_name=last_name,
                is_active=True,
                is_staff=False,
                is_superuser=False
            )
            user.set_unusable_password()
            user.save()
            
            # Create corresponding Client record
            Client.objects.create(
                user=user,
                first_name=first_name,
                last_name=last_name,
                email=email
            )
            
            created_count += 1
    
    print(f"✅ Freshbooks client import complete:")
    print(f"   Created: {created_count}")
    print(f"   Skipped: {skipped_count}")
    if created_count > 0:
        print(f"   Note: New users have no password. They must use password reset.")


def reverse_seed(apps, schema_editor):
    """Remove imported clients (optional - only run if you want to undo)."""
    # We don't reverse this to avoid accidentally deleting real users
    print("⚠️  Not removing users - this is a non-destructive migration")
    pass


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(seed_freshbooks_clients, reverse_seed),
    ]
