# Generated by Django 5.2.5 on 2026-01-24 23:51

from django.db import migrations


def seed_help_content(apps, schema_editor):
    """Populate help content automatically during migration."""
    HelpCategory = apps.get_model('help', 'HelpCategory')
    HelpArticle = apps.get_model('help', 'HelpArticle')
    FAQ = apps.get_model('help', 'FAQ')
    
    # Import and run the populate logic
    from help.management.commands.populate_help import Command
    command = Command()
    command.handle()


def reverse_seed(apps, schema_editor):
    """Remove seeded content if migration is reversed."""
    HelpCategory = apps.get_model('help', 'HelpCategory')
    HelpArticle = apps.get_model('help', 'HelpArticle')
    FAQ = apps.get_model('help', 'FAQ')
    
    # Delete all help content
    FAQ.objects.all().delete()
    HelpArticle.objects.all().delete()
    HelpCategory.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_help_content, reverse_seed),
    ]
