# Generated by Django 5.2.5 on 2025-08-21 18:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('style_image', models.ImageField(blank=True, null=True, upload_to='plans/styles')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'house style',
                'verbose_name_plural': 'house styles',
                'ordering': ['order', 'style_name'],
            },
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_number', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('square_footage', models.PositiveIntegerField(help_text='Total heated sq ft')),
                ('bedrooms', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('bathrooms', models.DecimalField(decimal_places=1, help_text='e.g. 2.5', max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('stories', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('garage_stalls', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('house_width_in', models.PositiveIntegerField(help_text='Overall width in inches')),
                ('house_depth_in', models.PositiveIntegerField(help_text='Overall depth in inches')),
                ('description', models.TextField(blank=True)),
                ('sku', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=180)),
                ('plan_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='plans/main')),
                ('is_available', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('house_style', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='plans.housestyle')),
            ],
            options={
                'verbose_name': 'plan',
                'verbose_name_plural': 'plans',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='PlanGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='plans/gallery')),
                ('kind', models.CharField(choices=[('front', 'Front Perspective'), ('floor', 'Floor Plan'), ('elevation', 'Elevation'), ('other', 'Other')], default='other', max_length=20)),
                ('caption', models.CharField(blank=True, max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='plans.plans')),
            ],
            options={
                'verbose_name': 'plan gallery image',
                'verbose_name_plural': 'plan gallery images',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='plans',
            index=models.Index(fields=['slug'], name='plans_plans_slug_b62a30_idx'),
        ),
        migrations.AddIndex(
            model_name='plans',
            index=models.Index(fields=['plan_number'], name='plans_plans_plan_nu_a75cac_idx'),
        ),
        migrations.AddIndex(
            model_name='plans',
            index=models.Index(fields=['house_style'], name='plans_plans_house_s_82aeb9_idx'),
        ),
        migrations.AddIndex(
            model_name='plans',
            index=models.Index(fields=['is_available', 'created_date'], name='plans_plans_is_avai_c00a5c_idx'),
        ),
        migrations.AddIndex(
            model_name='plans',
            index=models.Index(fields=['is_featured', 'created_date'], name='plans_plans_is_feat_f3c236_idx'),
        ),
    ]
