# Generated by Django 5.2.5 on 2026-01-22 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plans', models.ManyToManyField(related_name='in_comparisons', to='plans.plans')),
            ],
            options={
                'verbose_name': 'plan comparison',
                'verbose_name_plural': 'plan comparisons',
                'indexes': [models.Index(fields=['session_key', '-updated_at'], name='plans_planc_session_b4edbf_idx')],
            },
        ),
        migrations.CreateModel(
            name='SavedPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='plans.plans')),
            ],
            options={
                'verbose_name': 'saved plan',
                'verbose_name_plural': 'saved plans',
                'ordering': ['-saved_at'],
                'indexes': [models.Index(fields=['session_key', '-saved_at'], name='plans_saved_session_e7f3dc_idx')],
                'unique_together': {('session_key', 'plan')},
            },
        ),
    ]
