# Generated by Django 5.2.5 on 2026-01-22 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_remove_old_house_style'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='plans',
            name='plans_plans_house_s_82aeb9_idx',
        ),
    ]
