# Generated by Django 5.2.5 on 2026-05-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Partner site name', max_length=100)),
                ('key', models.CharField(editable=False, max_length=64, unique=True)),
                ('allowed_origins', models.TextField(blank=True, help_text='Comma-separated allowed origins, e.g. https://partnersite.com. Leave blank to allow any origin.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Partner API Key',
                'verbose_name_plural': 'Partner API Keys',
                'ordering': ['-created_at'],
            },
        ),
    ]
