# Generated by Django 5.2.5 on 2025-08-21 18:51

import django.core.validators
import django.db.models.deletion
import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About', max_length=120)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('owner_name', models.CharField(blank=True, max_length=120)),
                ('photo_main', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('photo_secondary', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('body', models.TextField(blank=True, help_text='One paragraph per line.')),
                ('highlights', models.TextField(blank=True, help_text='One item per line.')),
                ('badges', models.TextField(blank=True, help_text='One item per line.')),
                ('knowledge_skills', models.TextField(blank=True, help_text='Knowledge & skills — one item per line.')),
                ('licenses', models.TextField(blank=True, help_text='Licenses/registrations — one item per line.')),
                ('is_published', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About page',
                'verbose_name_plural': 'About page',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=160)),
                ('contact_name', models.CharField(blank=True, max_length=160)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=40)),
                ('contact_address', models.CharField(blank=True, max_length=200)),
                ('business_hours', models.TextField(blank=True, help_text="One entry per line, e.g. 'Mon–Fri: 9–5'")),
                ('brand_logo', models.ImageField(blank=True, null=True, upload_to='brand/')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referer', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied')], default='new', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='pages_conta_status_ac12d0_idx'), models.Index(fields=['email', 'created_at'], name='pages_conta_email_c82419_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('alt_email', models.EmailField(blank=True, max_length=254)),
                ('company', models.CharField(blank=True, max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('alt_phone_number', models.CharField(blank=True, max_length=20)),
                ('preferred_contact_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('text', 'Text')], default='email', max_length=10)),
                ('street_address', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('min_square_footage', models.PositiveIntegerField(blank=True, null=True)),
                ('max_square_footage', models.PositiveIntegerField(blank=True, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('number_of_floors', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('number_of_bedrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('number_of_bathrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('number_of_garage_spaces', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('land_purchased', models.BooleanField(default=False)),
                ('land_address', models.CharField(blank=True, max_length=100)),
                ('land_city', models.CharField(blank=True, max_length=50)),
                ('land_state', models.CharField(blank=True, max_length=50)),
                ('land_zip_code', models.CharField(blank=True, max_length=10)),
                ('land_size', models.CharField(blank=True, max_length=50)),
                ('pre_existing_plans', models.BooleanField(default=False)),
                ('foundation_height', models.CharField(blank=True, choices=[('crawl_space', 'Crawl Space'), ('8_ft', '8 ft'), ('9_ft', '9 ft'), ('10_ft', '10 ft'), ('other', 'Other')], max_length=20)),
                ('first_floor_height', models.CharField(blank=True, choices=[('8_ft', '8 ft'), ('9_ft', '9 ft'), ('10_ft', '10 ft'), ('other', 'Other')], max_length=20)),
                ('second_floor_height', models.CharField(blank=True, choices=[('8_ft', '8 ft'), ('9_ft', '9 ft'), ('10_ft', '10 ft'), ('other', 'Other')], max_length=20)),
                ('third_floor_height', models.CharField(blank=True, choices=[('8_ft', '8 ft'), ('9_ft', '9 ft'), ('10_ft', '10 ft'), ('other', 'Other')], max_length=20)),
                ('ceiling_feature_1', models.CharField(blank=True, choices=[('vaulted', 'Vaulted'), ('tray', 'Tray'), ('stepped', 'Stepped'), ('coffered', 'Coffered'), ('other', 'Other')], max_length=20)),
                ('ceiling_feature_2', models.CharField(blank=True, choices=[('vaulted', 'Vaulted'), ('tray', 'Tray'), ('stepped', 'Stepped'), ('coffered', 'Coffered'), ('other', 'Other')], max_length=20)),
                ('ceiling_feature_3', models.CharField(blank=True, choices=[('vaulted', 'Vaulted'), ('tray', 'Tray'), ('stepped', 'Stepped'), ('coffered', 'Coffered'), ('other', 'Other')], max_length=20)),
                ('additional_notes', models.TextField(blank=True)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('archived', 'Archived')], db_index=True, default='new', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('house_style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_inquiries', to='plans.housestyle')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='InquiryAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=pages.models.inquiry_upload_to)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='pages.projectinquiry')),
            ],
            options={
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BusinessHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('sun', 'Sunday'), ('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday')], max_length=3)),
                ('is_closed', models.BooleanField(default=False)),
                ('by_appointment', models.BooleanField(default=False)),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=100)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='pages.sitesettings')),
            ],
            options={
                'ordering': (models.Case(models.When(day='sun', then=models.Value(0)), models.When(day='mon', then=models.Value(1)), models.When(day='tue', then=models.Value(2)), models.When(day='wed', then=models.Value(3)), models.When(day='thu', then=models.Value(4)), models.When(day='fri', then=models.Value(5)), models.When(day='sat', then=models.Value(6)), default=models.Value(7), output_field=models.IntegerField()),),
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('rating', models.PositiveSmallIntegerField(help_text='1–5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('message', models.TextField()),
                ('consent_to_publish', models.BooleanField(default=False, help_text='Client gave consent to display this testimonial on the website.')),
                ('approved', models.BooleanField(default=False, help_text='Checked by staff; only approved + consented testimonials are visible.')),
                ('role', models.CharField(blank=True, choices=[('homeowner', 'Homeowner'), ('builder', 'Builder'), ('architect', 'Architect'), ('engineer', 'Engineer'), ('designer', 'Designer'), ('other', 'Other')], db_index=True, help_text='Reviewer role (e.g., Homeowner, Builder)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['approved', 'consent_to_publish', 'created_at'], name='pages_testi_approve_04f7fd_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='projectinquiry',
            index=models.Index(fields=['status', 'submitted_at'], name='pages_proje_status_5e204e_idx'),
        ),
        migrations.AddIndex(
            model_name='projectinquiry',
            index=models.Index(fields=['last_name', 'first_name'], name='pages_proje_last_na_5d283a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='businesshour',
            unique_together={('site', 'day')},
        ),
    ]
