# Generated by Django 5.2.5 on 2026-05-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebDesignInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('project_type', models.CharField(blank=True, choices=[('business_site', 'Business Website'), ('web_app', 'Web Application'), ('ecommerce', 'E-commerce Site'), ('redesign', 'Redesign / Refresh'), ('other', 'Other')], max_length=30)),
                ('message', models.TextField()),
                ('terms_accepted', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('archived', 'Archived')], db_index=True, default='new', max_length=16)),
            ],
            options={
                'verbose_name': 'Web design inquiry',
                'verbose_name_plural': 'Web design inquiries',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['status', 'submitted_at'], name='pages_webde_status_0a4412_idx')],
            },
        ),
    ]
