# Generated by Django 5.2.5 on 2026-06-01 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_webdesigninquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Pricing', max_length=120)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('included_heading', models.CharField(blank=True, default="What's Included", max_length=200)),
                ('included_body', models.TextField(blank=True, help_text='One bullet point per line. Lines starting with -, •, or — are stripped of the prefix.')),
                ('is_published', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pricing page',
                'verbose_name_plural': 'Pricing page',
            },
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='knowledge_skills',
            field=models.TextField(blank=True, help_text='Knowledge & skills - one item per line.'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='licenses',
            field=models.TextField(blank=True, help_text='Licenses/registrations - one item per line.'),
        ),
        migrations.CreateModel(
            name='PricingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="e.g. 'Custom Home Design'", max_length=150)),
                ('description', models.CharField(blank=True, help_text='Optional short description shown on the page.', max_length=300)),
                ('price_type', models.CharField(choices=[('flat', 'Flat Rate'), ('hourly', 'Per Hour')], default='flat', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_label', models.CharField(blank=True, help_text="Shown next to the price, e.g. 'per project', 'per page'.", max_length=60)),
                ('show_in_calculator', models.BooleanField(default=True, help_text='Include this item in the pricing calculator.')),
                ('default_quantity', models.DecimalField(decimal_places=1, default=1, help_text='Default quantity pre-filled in the calculator.', max_digits=8)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pages.pricingpage')),
            ],
            options={
                'verbose_name': 'Pricing item',
                'verbose_name_plural': 'Pricing items',
                'ordering': ['order', 'id'],
            },
        ),
    ]
