# Generated by Django 5.2.5 on 2026-06-09 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_pricingpage_alter_aboutpage_knowledge_skills_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('home_design', 'Home Design Products'), ('web_dev', 'Web / Coding Books & Tools')], db_index=True, help_text='Which page section this product appears in.', max_length=20)),
                ('url', models.URLField(help_text='Your full Amazon affiliate link (includes your Associates tag).', max_length=600, verbose_name='Affiliate URL')),
                ('image_url', models.URLField(blank=True, help_text='Optional. Paste a product image URL (e.g. the Amazon image address).', max_length=600, verbose_name='Image URL')),
                ('description', models.CharField(blank=True, help_text='Optional short blurb shown under the title.', max_length=300)),
                ('price_note', models.CharField(blank=True, help_text="Optional free text shown as the price, e.g. '$24.99' or 'From $19'.", max_length=40)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Affiliate product',
                'verbose_name_plural': 'Affiliate products',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['category', 'is_active', 'order'], name='pages_affil_categor_99cef4_idx')],
            },
        ),
    ]
