# Generated by Django 5.2.5 on 2026-06-09 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_affiliateproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliateproduct',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional. Use a compliant image link from Amazon SiteStripe (Get Link → Image) or the Product Advertising API — do not hotlink arbitrary product images. Leave blank to show a themed placeholder icon.', max_length=600, verbose_name='Image URL'),
        ),
    ]
