# Generated by Django 5.2.5 on 2026-07-21 20:38

from django.db import migrations, models


def neutralize_legacy_residential_pricing(apps, schema_editor):
    PricingPage = apps.get_model("pages", "PricingPage")
    PricingItem = apps.get_model("pages", "PricingItem")
    page = PricingPage.objects.filter(pk=1).first()
    if not page:
        return

    residential_copy = "new construction" in (page.subtitle or "").lower()
    residential_items = PricingItem.objects.filter(
        page=page,
        label__icontains="living area",
    ).exists()
    if not residential_copy and not residential_items:
        return

    page.title = "Web Services Pricing"
    page.subtitle = "Website projects are scoped around business goals, content, integrations, and support needs."
    page.included_heading = "Typical website project foundation"
    page.included_body = (
        "Responsive page design\n"
        "Content and call-to-action structure\n"
        "Contact or inquiry forms\n"
        "Accessibility and performance review\n"
        "Core search metadata and analytics\n"
        "Launch and handoff"
    )
    page.is_published = False
    page.save(
        update_fields=(
            "title",
            "subtitle",
            "included_heading",
            "included_body",
            "is_published",
        )
    )
    PricingItem.objects.filter(page=page).update(is_active=False)


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_projectinquiry_qualification_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='webdesigninquiry',
            name='budget_range',
            field=models.CharField(blank=True, choices=[('', 'Budget range (optional)'), ('under_3k', 'Under $3,000'), ('3k_7k', '$3,000-$7,000'), ('7k_15k', '$7,000-$15,000'), ('15k_plus', '$15,000+'), ('not_sure', 'Not sure yet')], max_length=20),
        ),
        migrations.AddField(
            model_name='webdesigninquiry',
            name='company_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='webdesigninquiry',
            name='current_website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='webdesigninquiry',
            name='timeline',
            field=models.CharField(blank=True, choices=[('', 'Desired timing (optional)'), ('asap', 'As soon as practical'), ('1_2_months', 'Within 1-2 months'), ('3_6_months', 'Within 3-6 months'), ('flexible', 'Flexible / exploring')], max_length=20),
        ),
        migrations.RunPython(
            neutralize_legacy_residential_pricing,
            migrations.RunPython.noop,
        ),
    ]
