# Generated by Django 5.2.5 on 2026-07-21 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_webdesigninquiry_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webdesigninquiry',
            name='source',
            field=models.CharField(blank=True, choices=[('', 'Direct / not specified'), ('home', 'Web homepage'), ('services_business', 'Services - business websites'), ('services_redesign', 'Services - redesigns'), ('services_app', 'Services - custom applications'), ('services_general', 'Services - general'), ('work', 'Selected work'), ('about', 'About'), ('pricing', 'Pricing'), ('region', 'Massachusetts and Rhode Island service area')], db_index=True, max_length=32),
        ),
    ]
